name: OISP
options:
  bundleIdPrefix: com.oisp
  deploymentTarget:
    macOS: "13.0"
  createIntermediateGroups: true
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  developmentLanguage: en
  minimumXcodeGenVersion: "2.36"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""  # Set your team ID
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    ENABLE_HARDENED_RUNTIME: YES
    DEAD_CODE_STRIPPING: YES

# Targets
targets:
  # Main App
  OISP:
    type: application
    platform: macOS
    sources:
      - path: OISPApp/Sources
        type: group
    resources:
      - path: OISPApp/Resources
        type: folder
    dependencies:
      - target: OISPCore
        embed: true
      - target: OISPNetworkExtensionBundle
        embed: true
        codeSign: true
        copy: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.oisp.app
        INFOPLIST_FILE: OISPApp/Info.plist
        CODE_SIGN_ENTITLEMENTS: OISPApp/OISP.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/../Frameworks"
        ENABLE_APP_SANDBOX: NO  # Network extensions need sandbox disabled
        SKIP_INSTALL: NO
        INFOPLIST_KEY_LSUIElement: YES  # Menu bar only app
        INFOPLIST_KEY_NSSystemExtensionUsageDescription: "OISP needs to install a network extension to capture AI API traffic."
    entitlements:
      path: OISPApp/OISP.entitlements
      properties:
        com.apple.developer.system-extension.install: true
        com.apple.developer.networking.networkextension:
          - app-proxy-provider
          - transparent-proxy-provider
          - content-filter-provider
        com.apple.developer.application-identifier: $(AppIdentifierPrefix)$(PRODUCT_BUNDLE_IDENTIFIER)
        com.apple.developer.team-identifier: $(DEVELOPMENT_TEAM)

  # OISPCore Framework
  OISPCore:
    type: framework
    platform: macOS
    sources:
      - path: OISPCore/Sources
        type: group
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.oisp.core
        INFOPLIST_FILE: OISPCore/Info.plist
        DEFINES_MODULE: YES
        PRODUCT_MODULE_NAME: OISPCore
        SKIP_INSTALL: YES
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/../Frameworks"
          - "@loader_path/Frameworks"
        OTHER_LDFLAGS:
          - "-lbsm"
    postCompileScripts: []

  # Network Extension System Extension Bundle
  OISPNetworkExtensionBundle:
    type: system-extension
    platform: macOS
    sources:
      - path: OISPNetworkExtension
        type: group
        excludes:
          - "*.md"
    dependencies:
      - target: OISPCore
        embed: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.oisp.networkextension
        INFOPLIST_FILE: OISPNetworkExtension/Info.plist
        CODE_SIGN_ENTITLEMENTS: OISPNetworkExtension/NetworkExtension.entitlements
        SKIP_INSTALL: YES
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/../Frameworks"
          - "@loader_path/Frameworks"
        SYSTEM_EXTENSION_PRODUCT_TYPE: com.apple.system-extension.network-extension
    entitlements:
      path: OISPNetworkExtension/NetworkExtension.entitlements
      properties:
        com.apple.developer.networking.networkextension:
          - app-proxy-provider
          - transparent-proxy-provider
        com.apple.developer.application-identifier: $(AppIdentifierPrefix)$(PRODUCT_BUNDLE_IDENTIFIER)
        com.apple.developer.team-identifier: $(DEVELOPMENT_TEAM)
        com.apple.security.app-sandbox: false
        com.apple.security.network.client: true
        com.apple.security.network.server: true

  # Unit Tests
  OISPTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: OISPCore/Tests
        type: group
    dependencies:
      - target: OISPCore
      - target: OISP
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.oisp.tests
        INFOPLIST_FILE: OISPCore/Tests/Info.plist
        GENERATE_INFOPLIST_FILE: YES

# Schemes
schemes:
  OISP:
    build:
      targets:
        OISP: all
        OISPCore: all
        OISPNetworkExtensionBundle: all
      preActions: []
    run:
      config: Debug
      disableMainThreadChecker: false
    test:
      targets:
        - OISPTests
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  OISPTests:
    build:
      targets:
        OISPTests: [test]
        OISPCore: [test]
    test:
      targets:
        - OISPTests
